/* ─────────────── LESSON DATA — Abu Shehadeh, Jaffa protest (28 June 2026) ───────────────
   Source: abu-shehadeh-speech.docx (approved reading edition, fully voweled), retokenized
   directly from the source paragraph text so punctuation is preserved: `punct` is a trailing
   mark rendered right after a word; `sep` is a standalone separator token (em dash / ellipsis).
   Sync has two layers:
   1) chunk-level start/end (paragraph highlight) — from transcript.txt raw segment boundaries.
   2) sentence-level `sentT` on a sentence's first word — each sentence (split at . or ؟) is
      matched via word-overlap to its best raw ASR segment (transcript.txt, reliable segment-
      level timestamps, NOT the noisy per-word attention data) and anchored to that segment's
      start time. This is the live "clause is being read now" highlight.
   Per-word `t` (from faster-whisper word_timestamps) is kept but UNUSED for highlighting —
   word-level ASR attention proved too unreliable for Arabic and was distracting; sentence-
   level anchored to real segment timestamps is the reconciliation the user asked for instead.
   Word-level Hebrew/English glosses are an AI-generated first draft, not yet teacher-reviewed.
*/
const CHUNKS = [
  { start:2.5, end:26, label:'0:02 – 0:26', text:[
    {w:"بَدّي",sentT:2.5,t:4.65,he:"אני רוצה",en:"I want",pos:null,root:null},
    {w:"أَرُدّ",t:5.55,he:"לענות",en:"to respond",pos:"verb",root:"رد"},
    {w:"عَلى",t:5.79,he:"על",en:"on",pos:null,root:null},
    {w:"بَعْض",t:6.21,he:"כמה מ",en:"some of",pos:null,root:null},
    {w:"الادِّعاءات",t:6.59,he:"הטענות",en:"the accusations",pos:null,root:null},
    {w:"اللّي",t:7.03,he:"ש-",en:"that/which",pos:null,root:null},
    {w:"بِتيجي",t:7.43,he:"שמגיעות",en:"that come",pos:"verb",root:"جي"},
    {w:"وبِتِسْأَل",punct:":",t:8.11,he:"ושואלות",en:"and ask",pos:"verb",root:"سأل"},
    {w:"إيش",t:8.31,he:"מה",en:"what",pos:null,root:null},
    {w:"الفايْدِة",t:8.63,he:"התועלת",en:"the benefit/point",pos:null,root:"فيد"},
    {w:"مِن",t:9.25,he:"מ-",en:"from",pos:null,root:null},
    {w:"هالوَقْفِة",punct:"؟",t:10.13,he:"העצרת הזאת",en:"this rally",pos:null,root:"وقف"},
    {w:"بِدّي",sentT:2.5,t:10.61,he:"אני רוצה",en:"I want",pos:null,root:null},
    {w:"أَرُدّ",t:11.27,he:"לענות",en:"to respond",pos:"verb",root:"رد"},
    {w:"عَلَيْكُم",punct:"،",t:12.15,he:"עליכם",en:"to you (pl.)",pos:null,root:null},
    {w:"وبِدّي",t:12.35,he:"ואני רוצה",en:"and I want",pos:null,root:null},
    {w:"أَسْأَل",punct:":",t:12.51,he:"לשאול",en:"to ask",pos:"verb",root:"سأل"},
    {w:"كيف",t:12.97,he:"איך",en:"how",pos:null,root:null},
    {w:"يَعْني",t:14.55,he:"כלומר",en:"meaning",pos:null,root:null},
    {w:"إِنّه",t:14.81,he:"ש-",en:"that",pos:null,root:null},
    {w:"مِنْضَلّ",t:15.41,he:"נישאר",en:"we remain",pos:"verb",root:"ضل"},
    {w:"ساكْتين",t:16.33,he:"שותקים",en:"silent (pl.)",pos:"verb",root:"سكت"},
    {w:"لَمّا",t:16.87,he:"כש-",en:"when",pos:null,root:null},
    {w:"تْلاتِة",t:17.91,he:"שלושה",en:"three",pos:null,root:null},
    {w:"بِنْقِتْلوا",t:18.19,he:"נרצחים",en:"are killed",pos:"verb",root:"قتل"},
    {w:"بِخِلال",t:18.37,he:"במהלך",en:"during",pos:null,root:null},
    {w:"تْلات",t:18.57,he:"שלושה",en:"three",pos:null,root:null},
    {w:"أَيّام",punct:"؟",t:18.83,he:"ימים",en:"days",pos:null,root:null},
  ]},
  { start:26, end:54, label:'0:26 – 0:54', text:[
    {w:"تْخَيَّلوا",sentT:26,t:22.43,he:"תארו לעצמכם",en:"imagine!",pos:"verb",root:"خيل"},
    {w:"إِنّه",t:22.67,he:"ש-",en:"that",pos:null,root:null},
    {w:"احْنا",t:23.43,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"نْحُطّ",t:24.79,he:"שמים",en:"put",pos:"verb",root:"حط"},
    {w:"حالْنا",t:25.11,he:"את עצמנו",en:"ourselves",pos:null,root:null},
    {w:"ساكْتين",punct:"،",t:25.45,he:"שותקים",en:"silent",pos:"verb",root:"سكت"},
    {w:"ونِتْعامَل",t:25.87,he:"ומתייחסים",en:"and deal with it",pos:"verb",root:"عامل"},
    {w:"وكَأَنّه",t:27.11,he:"וכאילו",en:"as if",pos:null,root:null},
    {w:"هادا",t:27.35,he:"זה",en:"this",pos:null,root:null},
    {w:"إِشي",t:27.69,he:"דבר",en:"thing",pos:null,root:null},
    {w:"عادي",punct:".",t:28.17,he:"רגיל",en:"normal",pos:null,root:null},
    {w:"لَمّا",sentT:26,t:29.63,he:"כש-",en:"when",pos:null,root:null},
    {w:"بْنُسْكُت",t:30.27,he:"אנחנו שותקים",en:"we go silent",pos:"verb",root:"سكت"},
    {w:"ونْضَلّ",t:31.77,he:"ונישארים",en:"and remain",pos:"verb",root:"ضل"},
    {w:"ساكْتين",punct:"،",t:31.97,he:"שותקים",en:"silent",pos:"verb",root:"سكت"},
    {w:"بِصير",t:32.43,he:"הופך",en:"becomes",pos:"verb",root:"صار"},
    {w:"القَتِل",t:33.51,he:"הרצח",en:"the killing",pos:null,root:"قتل"},
    {w:"عادي",punct:".",t:34.95,he:"רגיל",en:"normal",pos:null,root:null},
    {w:"وهاي",sentT:26,t:35.39,he:"וזאת",en:"and this is",pos:null,root:null},
    {w:"قيمِة",t:36.99,he:"הערך של",en:"the value of",pos:null,root:null},
    {w:"المُظاهَرة",t:37.47,he:"ההפגנה",en:"the demonstration",pos:null,root:null},
    {w:"والوَقْفِة",punct:":",t:37.75,he:"והעצרת",en:"and the rally",pos:null,root:"وقف"},
    {w:"إِنّه",t:37.89,he:"ש-",en:"that",pos:null,root:null},
    {w:"نْسَجِّل",t:38.29,he:"נרשום",en:"we register",pos:"verb",root:"سجل"},
    {w:"مَوْقِف",punct:".",t:38.91,he:"עמדה",en:"a stance",pos:null,root:"وقف"},
    {w:"آه",punct:"،",sentT:44,t:39.31,he:"אה",en:"ah",pos:null,root:null},
    {w:"بِدّنا",t:39.79,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"نْسَجِّل",t:40.13,he:"נרשום",en:"we register",pos:"verb",root:"سجل"},
    {w:"مَوْقِف",punct:".",t:40.51,he:"עמדה",en:"a stance",pos:null,root:"وقف"},
    {w:"هاي",sentT:44,t:40.89,he:"זאת",en:"this is",pos:null,root:null},
    {w:"مِش",t:41.43,he:"לא",en:"not",pos:null,root:null},
    {w:"الحالِة",t:41.63,he:"המצב",en:"the situation",pos:null,root:null},
    {w:"الطَّبيعِيِّة",punct:".",t:41.75,he:"הטבעי",en:"the normal",pos:null,root:null},
    {w:"فِيش",sentT:44,t:42.03,he:"אין",en:"there is no",pos:null,root:null},
    {w:"سَبَب",t:43.15,he:"סיבה",en:"reason",pos:null,root:null},
    {w:"بِالدُّنْيا",t:43.79,he:"בעולם",en:"in the world",pos:null,root:null},
    {w:"يْخَلّينا",t:44.83,he:"שיגרום לנו",en:"that makes us",pos:"verb",root:"خلي"},
    {w:"نِسْكُت",t:45.53,he:"לשתוק",en:"be silent",pos:"verb",root:"سكت"},
    {sep:"—"},
    {w:"احْنا",t:46.43,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"أَهِل",t:46.65,he:"בני",en:"people of",pos:null,root:null},
    {w:"هالبَلَد",punct:".",t:46.91,he:"הארץ הזאת",en:"this land",pos:null,root:"بلد"},
  ]},
  { start:54, end:81.9, label:'0:54 – 1:21', text:[
    {w:"فِيش",sentT:56,t:50.03,he:"אין",en:"there is no",pos:null,root:null},
    {w:"سَبَب",t:50.67,he:"סיבה",en:"reason",pos:null,root:null},
    {w:"لِيش",t:51.21,he:"למה",en:"why",pos:null,root:null},
    {w:"نِسْمَح",t:51.45,he:"נרשה",en:"we allow",pos:"verb",root:"سمح"},
    {w:"ونِتْعامَل",t:51.87,he:"ונתייחס",en:"and deal",pos:"verb",root:"عامل"},
    {w:"مَع",t:52.27,he:"עם",en:"with",pos:null,root:null},
    {w:"هالإِشي",t:52.61,he:"הדבר הזה",en:"this thing",pos:null,root:null},
    {w:"كَأَنّه",t:52.97,he:"כאילו",en:"as if",pos:null,root:null},
    {w:"طَبيعي",punct:".",t:53.23,he:"טבעי",en:"normal",pos:null,root:null},
    {w:"هادا",sentT:56,t:53.47,he:"זה",en:"this",pos:null,root:null},
    {w:"مِش",t:53.83,he:"לא",en:"not",pos:null,root:null},
    {w:"طَبيعي",t:55.39,he:"טבעי",en:"normal",pos:null,root:null},
    {w:"يا",t:55.85,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",punct:".",t:56.25,he:"חברים",en:"folks",pos:null,root:null},
    {w:"احْنا",sentT:56,t:57.09,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"أَهِل",t:58.39,he:"בני",en:"people of",pos:null,root:null},
    {w:"هالبَلَد",punct:"،",t:58.91,he:"הארץ הזאת",en:"this land",pos:null,root:"بلد"},
    {w:"مِش",t:59.05,he:"לא",en:"not",pos:null,root:null},
    {w:"مَقْطوعين",t:59.35,he:"מנותקים",en:"cut off",pos:"verb",root:"قطع"},
    {w:"مِن",t:59.87,he:"מ-",en:"from",pos:null,root:null},
    {w:"شَجَرة",punct:"،",t:60.05,he:"עץ",en:"a tree",pos:null,root:null},
    {w:"ومِش",t:60.37,he:"ולא",en:"and not",pos:null,root:null},
    {w:"راح",t:60.85,he:"הולכים",en:"going to",pos:"verb",root:"روح"},
    {w:"نْخَلّي",t:60.99,he:"ניתן ל-",en:"let",pos:"verb",root:"خلي"},
    {w:"عِصاباتِ",t:61.45,he:"לכנופיות",en:"the gangs of",pos:null,root:"عصب"},
    {w:"الجَريمِة",t:63.29,he:"הפשע",en:"crime",pos:null,root:null},
    {w:"تِحْكُم",t:63.53,he:"לשלוט ב",en:"to rule",pos:"verb",root:"حكم"},
    {w:"البَلَد",punct:".",t:63.91,he:"הארץ",en:"the land",pos:null,root:null},
    {w:"وكَمان",punct:"،",sentT:56,t:64.07,he:"וגם",en:"and also",pos:null,root:null},
    {w:"مِش",t:64.59,he:"לא",en:"not",pos:null,root:null},
    {w:"راح",t:65.59,he:"הולכים",en:"going to",pos:"verb",root:"روح"},
    {w:"نْخَلّي",t:65.75,he:"ניתן",en:"let",pos:"verb",root:"خلي"},
    {w:"اليَأْس",t:66.25,he:"לייאוש",en:"despair",pos:null,root:"يأس",sharedRoot:true},
    {w:"يِحْكُم",t:66.39,he:"לשלוט",en:"to rule",pos:"verb",root:"حكم"},
    {w:"البَلَد",t:66.87,he:"הארץ",en:"the land",pos:null,root:null},
    {w:"يا",t:68.27,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",punct:".",t:68.47,he:"חברים",en:"folks",pos:null,root:null},
    {w:"اليَأْس",sentT:56,t:68.99,he:"הייאוש",en:"despair",pos:null,root:"يأس",sharedRoot:true},
    {w:"مِش",t:69.59,he:"לא",en:"not",pos:null,root:null},
    {w:"مَشْروع",t:70.03,he:"פרויקט",en:"a project",pos:null,root:null},
    {w:"سِياسي",punct:"،",t:70.39,he:"פוליטי",en:"political",pos:null,root:null},
    {w:"وما",t:72.23,he:"ולא",en:"and not",pos:null,root:null},
    {w:"بْساعِدْنا",t:73.15,he:"עוזר לנו",en:"helps us",pos:"verb",root:"ساعد"},
    {w:"بِإِشي",punct:".",t:73.79,he:"בכלום",en:"in anything",pos:null,root:null},
  ]},
  { start:81.9, end:98.2, label:'1:21 – 1:38', text:[
    {w:"آه",punct:"،",sentT:81.9,t:78.01,he:"אה",en:"ah",pos:null,root:null},
    {w:"الوَضِع",t:78.71,he:"המצב",en:"the situation",pos:null,root:null},
    {w:"صَعِب",punct:".",t:79.03,he:"קשה",en:"difficult",pos:null,root:null},
    {w:"آه",punct:"،",sentT:81.9,t:79.45,he:"אה",en:"ah",pos:null,root:null},
    {w:"الوَضِع",t:79.59,he:"המצב",en:"the situation",pos:null,root:null},
    {w:"حَزين",punct:".",t:79.61,he:"עצוב",en:"sad",pos:null,root:null},
    {w:"بَسْ",sentT:84.6,t:79.71,he:"אבל",en:"but",pos:null,root:null},
    {w:"إيش",t:80.11,he:"מה",en:"what",pos:null,root:null},
    {w:"لازِم",t:80.59,he:"צריך",en:"must",pos:null,root:null},
    {w:"يْكون",t:80.77,he:"להיות",en:"be",pos:"verb",root:"كان"},
    {w:"رَدّنا",punct:"؟",t:81.41,he:"התגובה שלנו",en:"our response",pos:null,root:"رد"},
    {w:"لازِم",sentT:86.5,t:82.65,he:"צריך",en:"must",pos:null,root:null},
    {w:"نِبْني",t:82.99,he:"לבנות",en:"we build",pos:"verb",root:"بني"},
    {w:"إِشي",t:83.45,he:"דבר",en:"something",pos:null,root:null},
    {sep:"—"},
    {w:"لِلنّاس",punct:"،",t:83.73,he:"לאנשים",en:"for the people",pos:null,root:null},
    {w:"لِلوْلاد",punct:"،",t:84.03,he:"לילדים",en:"for the children",pos:null,root:null},
    {w:"لِلمُسْتَقْبَل",punct:".",t:84.51,he:"לעתיד",en:"for the future",pos:null,root:null},
    {w:"المُسْتَقْبَل",sentT:87.2,t:85.19,he:"העתיד",en:"the future",pos:null,root:null},
    {w:"مُمْكِن",t:85.39,he:"אפשר",en:"possible",pos:null,root:null},
    {w:"يْكون",t:85.57,he:"להיות",en:"be",pos:"verb",root:"كان"},
    {w:"أَحْسَن",punct:".",t:85.83,he:"טוב יותר",en:"better",pos:null,root:null},
    {w:"بَسْ",sentT:93,t:85.91,he:"אבל",en:"but",pos:null,root:null},
    {w:"كيف",t:86.13,he:"איך",en:"how",pos:null,root:null},
    {w:"بِصير",t:86.41,he:"יהיה",en:"will become",pos:"verb",root:"صار"},
    {w:"أَحْسَن",t:86.65,he:"טוב יותר",en:"better",pos:null,root:null},
    {w:"لَمّا",t:86.91,he:"כש-",en:"when",pos:null,root:null},
    {w:"نْضَلّ",t:87.11,he:"נישאר",en:"we remain",pos:"verb",root:"ضل"},
    {w:"ساكْتين",punct:"،",t:87.95,he:"שותקים",en:"silent",pos:"verb",root:"سكت"},
    {w:"ونْضَلّ",t:91.41,he:"ונישאר",en:"and remain",pos:"verb",root:"ضل"},
    {w:"بِالبْيوت",punct:"،",t:92.21,he:"בבתים",en:"at home",pos:null,root:"بيت"},
    {w:"وما",t:92.53,he:"ולא",en:"and not",pos:null,root:null},
    {w:"نْسَوّي",t:92.71,he:"עושים",en:"do",pos:"verb",root:"سوي"},
    {w:"إِشي",punct:"؟",t:92.99,he:"כלום",en:"anything",pos:null,root:null},
  ]},
  { start:98.2, end:133.3, label:'1:38 – 2:13', text:[
    {w:"يا",sentT:103.4,t:115.03,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",punct:"،",t:115.65,he:"חברים",en:"folks",pos:null,root:null},
    {w:"هادا",t:116.31,he:"זה",en:"this",pos:null,root:null},
    {w:"نَصيبْنا",punct:"؟",t:116.87,he:"הגורל שלנו",en:"our fate",pos:null,root:"نصب"},
    {w:"احْنا",sentT:129.2,t:117.47,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"أَبْناء",t:118.03,he:"בני",en:"sons of",pos:null,root:null},
    {w:"الشَّعِب",t:118.69,he:"העם",en:"the people",pos:null,root:null},
    {w:"العَرَبي",t:119.55,he:"הערבי",en:"the Arab",pos:null,root:null},
    {w:"الفَلَسْطيني",t:119.71,he:"הפלסטיני",en:"the Palestinian",pos:null,root:null},
    {sep:"—"},
    {w:"هادا",t:120.07,he:"זה",en:"this",pos:null,root:null},
    {w:"نَصيبْنا",punct:"؟",t:120.43,he:"הגורל שלנו",en:"our fate",pos:null,root:"نصب"},
    {w:"إِنّه",sentT:133.3,t:120.97,he:"ש-",en:"that",pos:null,root:null},
    {w:"نْعيش",t:122.39,he:"לחיות",en:"we live",pos:"verb",root:"عيش"},
    {w:"بِدَوْلِة",t:122.97,he:"במדינה",en:"in a state",pos:null,root:null},
    {w:"ومُؤَسَّسِة",t:123.37,he:"ומוסד",en:"and institution",pos:null,root:null},
    {w:"عُنْصُرِيِّة",punct:"،",t:124.35,he:"גזעני",en:"racist",pos:null,root:null},
    {w:"وشُرْطة",t:124.69,he:"ומשטרה",en:"and a police force",pos:null,root:null},
    {w:"مَشْغولِة",t:124.83,he:"עסוקה",en:"busy",pos:"verb",root:"شغل"},
    {w:"بِإِشي",t:124.91,he:"בדבר",en:"with a thing",pos:null,root:null},
    {w:"واحَد",t:125.21,he:"אחד",en:"one",pos:null,root:null},
    {w:"بَس",punct:"،",t:125.53,he:"רק",en:"only",pos:null,root:null},
    {w:"عَ",t:125.81,he:"על",en:"by",pos:null,root:null},
    {w:"فِكْرة",punct:":",t:127.69,he:"רעיון / דרך אגב",en:"by the way",pos:null,root:null},
    {w:"مَشْغولين",t:128.45,he:"עסוקים",en:"busy",pos:"verb",root:"شغل"},
    {w:"يْلاحْقوا",t:129.09,he:"לרדוף אחרי",en:"chasing",pos:"verb",root:"لحق"},
    {w:"عُمّالِ",t:129.15,he:"פועלי",en:"workers of",pos:null,root:"عمل"},
    {w:"الضِّفِّة",punct:".",t:129.83,he:"הגדה",en:"the West Bank",pos:null,root:null},
    {w:"مُهِمّ",t:130.13,he:"חשוב",en:"important",pos:null,root:null},
    {w:"تَعْرْفوا",t:130.49,he:"שתדעו",en:"that you know",pos:"verb",root:"عرف"},
    {w:"إِنّه",t:130.87,he:"ש-",en:"that",pos:null,root:null},
    {w:"الشُّرْطة",t:131.03,he:"המשטרה",en:"the police",pos:null,root:null},
    {w:"بِالمَنْطِقة",t:131.11,he:"באזור",en:"in the area",pos:null,root:null},
    {w:"ما",t:132.13,he:"לא",en:"not",pos:null,root:null},
    {w:"بْتِعْمَل",t:132.89,he:"עושה",en:"does",pos:"verb",root:"عمل"},
    {w:"وَلا",t:133.25,he:"ולא (אפילו)",en:"not even",pos:null,root:null},
    {w:"إِشي",t:133.65,he:"דבר",en:"a thing",pos:null,root:null},
    {w:"بِما",he:"במה ש",en:"regarding what",pos:null,root:null},
    {w:"يْخُصّ",he:"נוגע ל",en:"concerns",pos:"verb",root:"خص"},
    {w:"العُنِف",he:"האלימות",en:"the violence",pos:null,root:null},
    {w:"والجَريمِة",punct:".",he:"והפשע",en:"and crime",pos:null,root:null},
    {w:"مَشْغولين",sentT:133.3,he:"עסוקים",en:"busy",pos:"verb",root:"شغل"},
    {w:"بِمُلاحْقِة",he:"ברדיפה אחרי",en:"with chasing",pos:null,root:"لحق"},
    {w:"عُمّالِ",he:"פועלי",en:"workers of",pos:null,root:"عمل"},
    {w:"الضِّفِّة",punct:"،",he:"הגדה",en:"the West Bank",pos:null,root:null},
    {w:"اللّي",he:"ש-",en:"who",pos:null,root:null},
    {w:"هُمّ",he:"הם",en:"they",pos:null,root:null},
    {w:"كَمان",he:"גם",en:"also",pos:null,root:null},
    {w:"مَساكين",he:"מסכנים",en:"poor/pitiful",pos:null,root:null},
    {w:"بِدّهُم",he:"הם רוצים",en:"they want",pos:null,root:null},
    {w:"بَس",he:"רק",en:"only",pos:null,root:null},
    {w:"يِتْرَزْقوا",punct:".",he:"להתפרנס",en:"to earn a living",pos:"verb",root:"رزق"},
    {w:"هاي",he:"זאת",en:"this is",pos:null,root:null},
    {w:"هِيَّ",he:"היא",en:"it is",pos:null,root:null},
    {w:"الشُّرْطة",punct:".",he:"המשטרה",en:"the police",pos:null,root:null},
    {w:"هادا",sentT:133.3,he:"זו",en:"this is",pos:null,root:null},
    {w:"الواقِع",he:"המציאות",en:"the reality",pos:null,root:"وقع"},
    {w:"اللّي",he:"ש-",en:"that",pos:null,root:null},
    {w:"احْنا",he:"אנחנו",en:"we",pos:null,root:null},
    {w:"عايْشين",he:"חיים",en:"living",pos:"verb",root:"عيش"},
    {w:"فيه",punct:".",he:"בה",en:"in it",pos:null,root:null},
  ]},
  { start:133.3, end:180, label:'2:13 – 3:00', text:[
    {w:"اليَوم",sentT:143.2,t:158.01,he:"היום",en:"today",pos:null,root:null},
    {w:"كُنْت",t:158.65,he:"הייתי",en:"I was",pos:"verb",root:"كان"},
    {w:"بَحْكي",t:158.87,he:"מדבר",en:"talking",pos:"verb",root:"حكي"},
    {w:"مَع",t:159.19,he:"עם",en:"with",pos:null,root:null},
    {w:"واحَد",t:159.67,he:"אחד",en:"one",pos:null,root:null},
    {w:"مِن",t:159.97,he:"מ-",en:"from",pos:null,root:null},
    {w:"الشَّباب",punct:"،",t:160.37,he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"وقُلْت",t:160.79,he:"ואמרתי",en:"and I said",pos:"verb",root:"قال"},
    {w:"لُه",t:161.03,he:"לו",en:"to him",pos:null,root:null},
    {w:"إِنّه",t:161.29,he:"ש-",en:"that",pos:null,root:null},
    {w:"المَوْقِف",t:161.51,he:"העמדה",en:"the stance",pos:null,root:"وقف"},
    {w:"الطَّبيعي",t:161.87,he:"הטבעית",en:"the natural",pos:null,root:null},
    {w:"لِأَهِل",t:162.17,he:"לבני",en:"for the people of",pos:null,root:null},
    {w:"البَلَد",t:162.95,he:"הארץ",en:"the land",pos:null,root:null},
    {w:"هُوّ",t:163.93,he:"היא",en:"it is",pos:null,root:null},
    {w:"إِنّه",t:164.57,he:"ש-",en:"that",pos:null,root:null},
    {w:"نْطالِب",t:165.05,he:"אנחנו דורשים",en:"we demand",pos:"verb",root:"طلب"},
    {w:"بِإِقالِة",t:165.27,he:"בפיטורים של",en:"the dismissal of",pos:null,root:"قال"},
    {w:"قائِد",t:165.63,he:"מפקד",en:"commander",pos:null,root:"قود"},
    {w:"مَحَطِّة",t:165.97,he:"תחנת",en:"station of",pos:null,root:null},
    {w:"الشُّرْطة",punct:".",t:166.35,he:"המשטרה",en:"the police",pos:null,root:null},
    {w:"قال",sentT:147.4,t:166.75,he:"אמר",en:"he said",pos:"verb",root:"قال"},
    {w:"لي",punct:":",t:177.01,he:"לי",en:"to me",pos:null,root:null},
    {w:"لِيش",punct:"؟",t:177.77,he:"למה",en:"why",pos:null,root:null},
    {w:"قُلْت",sentT:152.4,t:178.55,he:"אמרתי",en:"I said",pos:"verb",root:"قال"},
    {w:"لُه",punct:":",t:178.73,he:"לו",en:"to him",pos:null,root:null},
    {w:"لَأَنّه",t:179.29,he:"כי",en:"because",pos:null,root:null},
    {w:"فِشِل",punct:"،",t:179.53,he:"נכשל",en:"he failed",pos:"verb",root:"فشل"},
    {w:"الزَّلَمِة",t:180.05,he:"הבן-אדם",en:"the guy",pos:null,root:null},
    {w:"فِشِل",punct:".",t:180.15,he:"נכשל",en:"failed",pos:"verb",root:"فشل"},
    {w:"قال",sentT:152.4,t:181.11,he:"אמר",en:"he said",pos:"verb",root:"قال"},
    {w:"لي",punct:":",t:181.87,he:"לי",en:"to me",pos:null,root:null},
    {w:"مين",t:181.99,he:"מי",en:"who",pos:null,root:null},
    {w:"بِيعْرِف",punct:"،",t:182.57,he:"יודע",en:"knows",pos:"verb",root:"عرف"},
    {w:"بِيْجوز",t:182.99,he:"יכול להיות",en:"maybe",pos:"verb",root:"جوز"},
    {w:"هاي",he:"אלה",en:"these are",pos:null,root:null},
    {w:"أَهْدافُه",he:"המטרות שלו",en:"his goals",pos:null,root:"هدف"},
    {w:"أَصْلاً",punct:".",he:"בכלל",en:"to begin with",pos:null,root:null},
    {w:"شايْفين",punct:"؟",he:"רואים",en:"you see",pos:"verb",root:"شوف"},
    {w:"احْنا",sentT:160.7,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"كَبَلَد",punct:"،",he:"כמדינה",en:"as a country",pos:null,root:null},
    {w:"كَناس",he:"כאנשים",en:"as people",pos:null,root:null},
    {w:"طَبيعِيِّين",punct:"،",he:"רגילים",en:"normal (pl.)",pos:null,root:null},
    {w:"لَمّا",he:"כש-",en:"when",pos:null,root:null},
    {w:"يْصير",he:"קורה",en:"happens",pos:"verb",root:"صار"},
    {w:"تْلات",he:"שלושה",en:"three",pos:null,root:null},
    {w:"حالاتِ",he:"מקרי",en:"cases of",pos:null,root:null},
    {w:"قَتِل",he:"רצח",en:"killing",pos:null,root:"قتل"},
    {w:"بِخِلال",he:"במהלך",en:"during",pos:null,root:null},
    {w:"تْلات",he:"שלושה",en:"three",pos:null,root:null},
    {w:"أَيّام",punct:"،",he:"ימים",en:"days",pos:null,root:null},
    {w:"الطَّبيعي",he:"הטבעי",en:"the natural (thing)",pos:null,root:null},
    {w:"إِنّه",he:"ש-",en:"that",pos:null,root:null},
    {w:"قائِد",he:"מפקד",en:"commander",pos:null,root:"قود"},
    {w:"المَحَطّة",he:"התחנה",en:"the station",pos:null,root:null},
    {w:"يِسْتَحي",he:"מתבייש",en:"feels ashamed",pos:"verb",root:"حيي"},
    {w:"مِن",he:"מ-",en:"of",pos:null,root:null},
    {w:"حالُه",he:"מעצמו",en:"himself",pos:null,root:null},
    {w:"ويْقول",punct:":",he:"ואומר",en:"and says",pos:"verb",root:"قال"},
    {w:"أَنا",he:"אני",en:"I",pos:null,root:null},
    {w:"فِشِلْت",punct:"،",he:"נכשלתי",en:"I failed",pos:"verb",root:"فشل"},
    {w:"أَنا",he:"אני",en:"I",pos:null,root:null},
    {w:"فاشِل",punct:"،",he:"כישלון",en:"a failure",pos:null,root:"فشل"},
    {w:"وبَروح",punct:".",he:"והולך",en:"and leaves",pos:"verb",root:"روح"},
    {w:"هادا",sentT:160.7,he:"זה",en:"this",pos:null,root:null},
    {w:"الوَضِع",he:"המצב",en:"the situation",pos:null,root:null},
    {w:"الطَّبيعي",punct:".",he:"הטבעי",en:"the natural",pos:null,root:null},
    {w:"قائِد",sentT:165.2,he:"מפקד",en:"commander",pos:null,root:"قود"},
    {w:"مَحَطّة",he:"תחנת",en:"station",pos:null,root:null},
    {w:"بِيفْشَل",he:"נכשל",en:"fails",pos:"verb",root:"فشل"},
    {w:"بِهالطَّريقة",punct:"،",he:"בצורה הזאת",en:"in this way",pos:null,root:null},
    {w:"بِروح",punct:"،",he:"הולך",en:"goes",pos:"verb",root:"روح"},
    {w:"مِن",he:"מ-",en:"of",pos:null,root:null},
    {w:"حالُه",punct:".",he:"מעצמו",en:"himself",pos:null,root:null},
  ]},
  { start:180, end:193.1, label:'3:00 – 3:13', text:[
    {w:"عِنّا",sentT:174.1,t:185.71,he:"יש לנו",en:"we have",pos:null,root:null},
    {w:"كَم",t:186.17,he:"כמה",en:"a few",pos:null,root:null},
    {w:"خَطْوة",t:186.57,he:"צעד",en:"step",pos:null,root:null},
    {w:"نَقَشْناها",t:187.09,he:"תכננו אותה",en:"we mapped it out",pos:"verb",root:"نقش"},
    {w:"اليَوم",t:187.37,he:"היום",en:"today",pos:null,root:null},
    {w:"سَوا",t:187.65,he:"יחד",en:"together",pos:null,root:null},
    {w:"بِالهَيْئة",t:188.11,he:"בוועדה",en:"with the committee",pos:null,root:null},
    {w:"الإِسْلامِيِّة",punct:".",t:188.39,he:"האסלאמית",en:"the Islamic",pos:null,root:null},
    {w:"بْنُطالِب",sentT:184.7,t:189.19,he:"אנחנו דורשים",en:"we demand",pos:"verb",root:"طلب"},
    {w:"بِإِقالِة",t:189.67,he:"בפיטורים של",en:"the dismissal of",pos:null,root:"قال"},
    {w:"قائِد",t:190.69,he:"מפקד",en:"commander",pos:null,root:"قود"},
    {w:"مَحَطِّة",t:191.33,he:"תחנת",en:"station of",pos:null,root:null},
    {w:"الشُّرْطة",punct:"،",t:191.89,he:"המשטרה",en:"the police",pos:null,root:null},
    {w:"وراح",t:192.01,he:"ונלך ל-",en:"and will",pos:"verb",root:"روح"},
    {w:"نْطَلِّع",t:192.41,he:"נוציא",en:"bring out",pos:"verb",root:"طلع"},
    {w:"عَريضة",punct:"،",t:192.77,he:"עצומה",en:"a petition",pos:null,root:null},
    {w:"وبِتْساعْدونا",t:193.11,he:"ותעזרו לנו",en:"and you'll help us",pos:"verb",root:"ساعد"},
    {w:"فيها",punct:"،",t:193.45,he:"בה",en:"with it",pos:null,root:null},
    {w:"وراح",t:193.95,he:"ונלך ל-",en:"and will",pos:"verb",root:"روح"},
    {w:"نْوَصِّلْها",t:195.05,he:"נעביר אותה",en:"we'll deliver it",pos:"verb",root:"وصل"},
    {w:"لَكُلّ",t:195.81,he:"לכל",en:"to all",pos:null,root:null},
    {w:"الجِهات",t:196.77,he:"הגורמים",en:"the parties",pos:null,root:null},
    {w:"اللّي",t:197.01,he:"ש-",en:"that",pos:null,root:null},
    {w:"لازِم",he:"צריך",en:"must",pos:null,root:null},
    {w:"توصَلْها",punct:".",he:"שתגיע אליהם",en:"it must reach",pos:"verb",root:"وصل"},
  ]},
  { start:193.1, end:245.7, label:'3:13 – 4:05', text:[
    {w:"الإِشي",sentT:193.1,t:217.91,he:"הדבר",en:"the thing",pos:null,root:null},
    {w:"التّاني",t:218.79,he:"השני",en:"second",pos:null,root:null},
    {w:"يا",t:219.83,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",t:220.25,he:"חברים",en:"folks",pos:null,root:null},
    {sep:"—"},
    {w:"وهون",t:220.69,he:"וכאן",en:"and here",pos:null,root:null},
    {w:"بِدّنا",t:221.17,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"مُساعَدة",t:221.77,he:"עזרה",en:"help",pos:null,root:"ساعد"},
    {w:"مِن",t:222.35,he:"מ-",en:"from",pos:null,root:null},
    {w:"الأَخَوات",punct:".",t:222.83,he:"האחיות",en:"the sisters",pos:null,root:null},
    {w:"الشَّباب",sentT:204.3,t:223.37,he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"اللّي",t:224.07,he:"ש-",en:"who",pos:null,root:null},
    {w:"راحوا",t:224.51,he:"הלכו",en:"passed away",pos:"verb",root:"روح"},
    {w:"عَ",t:224.95,he:"במהלך",en:"over",pos:null,root:null},
    {w:"مَرّ",t:225.57,he:"מהלך",en:"the course of",pos:null,root:"مر"},
    {w:"السِّنين",punct:"…",t:226.29,he:"השנים",en:"the years",pos:null,root:null},
    {w:"بِتْمُرّ",t:226.71,he:"עוברות",en:"pass",pos:"verb",root:"مر"},
    {w:"عَلَيْنا",t:227.33,he:"עלינו",en:"over us",pos:null,root:null},
    {w:"سِنين",t:227.53,he:"שנים",en:"years",pos:null,root:null},
    {w:"وكَأَنّه",t:228.15,he:"וכאילו",en:"as if it were",pos:null,root:null},
    {w:"أَوّل",t:228.73,he:"הראשון",en:"the first",pos:null,root:null},
    {w:"يَوم",t:233.31,he:"יום",en:"day",pos:null,root:null},
    {w:"لَمّا",t:234.15,he:"כש-",en:"when",pos:null,root:null},
    {w:"فَقَدوا",t:234.51,he:"איבדו",en:"they lost",pos:"verb",root:"فقد"},
    {w:"الوَلَد",punct:"،",t:234.99,he:"הבן",en:"the son",pos:null,root:null},
    {w:"وهاي",t:235.23,he:"וזאת",en:"and this",pos:null,root:null},
    {w:"الأُمّ",t:235.57,he:"האמא",en:"the mother",pos:null,root:null},
    {w:"لِسّاتها",t:236.17,he:"עדיין",en:"still",pos:null,root:null},
    {w:"بْنَفْس",t:236.59,he:"באותו",en:"in the same",pos:null,root:null},
    {w:"الوَجَع",punct:".",t:236.83,he:"כאב",en:"pain",pos:null,root:null},
    {w:"فَعِنّا",sentT:208.6,t:237.27,he:"ולכן יש לנו",en:"so we have",pos:null,root:null},
    {w:"طَلَب",t:242.13,he:"בקשה",en:"a request",pos:null,root:"طلب"},
    {w:"خاصّ",t:242.97,he:"מיוחדת",en:"special",pos:null,root:null},
    {w:"لِلنِّسْوان",punct:".",t:243.31,he:"לנשים",en:"for the women",pos:null,root:null},
    {w:"احْنا",sentT:214.9,t:243.51,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"بِالهَيْئة",t:243.67,he:"בוועדה",en:"in the committee",pos:null,root:null},
    {w:"الإِسْلامِيِّة",t:245.41,he:"האסלאמית",en:"the Islamic",pos:null,root:null},
    {w:"قَرَّرْنا",t:246.21,he:"החלטנו",en:"we decided",pos:"verb",root:"قرر"},
    {w:"إِنّه",t:246.41,he:"ש-",en:"that",pos:null,root:null},
    {w:"يَوم",t:246.97,he:"יום",en:"day",pos:null,root:null},
    {w:"الخَميس",punct:"،",t:247.11,he:"חמישי",en:"Thursday",pos:null,root:null},
    {w:"بَعِد",t:248.29,he:"אחרי",en:"after",pos:null,root:null},
    {w:"بْيوت",t:249.05,he:"בתי",en:"the houses of",pos:null,root:null},
    {w:"العَزا",punct:"،",t:249.35,he:"האבל",en:"the mourning",pos:null,root:null},
    {w:"بِدّنا",he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"نْنُصُب",he:"נקים",en:"we'll erect",pos:"verb",root:"نصب"},
    {w:"بِحَديقِة",he:"בגן",en:"in the garden of",pos:null,root:null},
    {w:"الغَزازْوة",he:"אל-ע׳זאזווה",en:"al-Ghazazwe",pos:null,root:null},
    {w:"خِيمِة",he:"אוהל",en:"a tent of",pos:null,root:null},
    {w:"اعْتِصام",punct:"،",he:"ישיבת מחאה",en:"sit-in protest",pos:null,root:null},
    {w:"وبِدّنا",he:"ואנחנו רוצים",en:"and we want",pos:null,root:null},
    {w:"الأُمَّهات",he:"האמהות",en:"the mothers",pos:null,root:null},
    {w:"والأَخَوات",he:"והאחיות",en:"and the sisters",pos:null,root:null},
    {w:"يِجوا",he:"שיבואו",en:"to come",pos:"verb",root:"جي"},
    {w:"يِحْكوا",he:"שיספרו",en:"to tell",pos:"verb",root:"حكي"},
    {w:"قِصَصْهُن",he:"הסיפורים שלהן",en:"their stories",pos:null,root:"قصص"},
    {sep:"—"},
    {w:"عَشان",he:"כדי ש",en:"so that",pos:null,root:null},
    {w:"الشَّباب",he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"يِسْمَعوا",he:"שישמעו",en:"hear",pos:"verb",root:"سمع"},
    {w:"إيش",he:"מה",en:"what",pos:null,root:null},
    {w:"بِصير",he:"קורה",en:"happens",pos:"verb",root:"صار"},
    {w:"لَمّا",he:"כש-",en:"when",pos:null,root:null},
    {w:"الوَلَد",he:"הבן",en:"the son",pos:null,root:null},
    {w:"بِيموت",punct:".",he:"מת",en:"dies",pos:"verb",root:"موت"},
    {w:"إيش",sentT:224.1,he:"מה",en:"what",pos:null,root:null},
    {w:"بِتْمُرّ",he:"עובר",en:"happens to",pos:"verb",root:"مر"},
    {w:"فيه",he:"בה",en:"to her",pos:null,root:null},
    {w:"الأُمّ",he:"האמא",en:"the mother",pos:null,root:null},
    {w:"لَمّا",he:"כש-",en:"when",pos:null,root:null},
    {w:"ابْنْها",he:"הבן שלה",en:"her son",pos:null,root:null},
    {w:"بِنْقِتِل",punct:"؟",he:"נהרג",en:"is killed",pos:"verb",root:"قتل"},
    {w:"عَشان",sentT:229.3,he:"כדי ש",en:"so that",pos:null,root:null},
    {w:"باقي",he:"שאר",en:"the rest of",pos:null,root:"بقي"},
    {w:"الشَّباب",punct:"،",he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"إذا",he:"אם",en:"if",pos:null,root:null},
    {w:"سِمْعوا",he:"שמעו",en:"they heard",pos:"verb",root:"سمع"},
    {w:"هالقِصَص",punct:"،",he:"הסיפורים האלה",en:"these stories",pos:null,root:null},
    {w:"يِفْهَموا",he:"יבינו",en:"understand",pos:"verb",root:"فهم"},
    {w:"كيف",he:"איך",en:"how",pos:null,root:null},
    {w:"بِتِحْرَق",he:"נשרפים",en:"burn",pos:"verb",root:"حرق"},
    {w:"قْلوب",he:"לבבות",en:"hearts of",pos:null,root:"قلب"},
    {w:"الأُمَّهات",punct:"،",he:"האמהות",en:"the mothers",pos:null,root:null},
    {w:"وكيف",he:"ואיך",en:"and how",pos:null,root:null},
    {w:"بِتِحْرَق",he:"נשרפים",en:"burn",pos:"verb",root:"حرق"},
    {w:"قْلوبْنا",he:"הלבבות שלנו",en:"our hearts",pos:null,root:null},
    {w:"احْنا",he:"אנחנו",en:"we",pos:null,root:null},
    {w:"كَمان",punct:".",he:"גם",en:"also",pos:null,root:null},
    {w:"وفِيش",sentT:240.8,he:"ואין",en:"and there is no",pos:null,root:null},
    {w:"سَبَب",he:"סיבה",en:"reason",pos:null,root:null},
    {w:"يْخَلّي",he:"שיגרום",en:"that makes",pos:"verb",root:"خلي"},
    {w:"هادا",he:"זה",en:"this",pos:null,root:null},
    {w:"يْكون",he:"להיות",en:"be",pos:"verb",root:"كان"},
    {w:"طَبيعي",punct:".",he:"טבעי",en:"normal",pos:null,root:null},
  ]},
  { start:245.7, end:300.4, label:'4:05 – 5:00', text:[
    {w:"فَرَجاءً",sentT:245.7,t:281.03,he:"אז בבקשה",en:"so please",pos:null,root:null},
    {w:"مِن",t:281.67,he:"מ-",en:"from",pos:null,root:null},
    {w:"الأَخَوات",t:282.01,he:"האחיות",en:"the sisters",pos:null,root:null},
    {w:"إِنّهُن",t:282.23,he:"ש-הן",en:"that they (f.)",pos:null,root:null},
    {w:"يْساعْدونا",punct:".",t:282.95,he:"יעזרו לנו",en:"help us",pos:"verb",root:"ساعد"},
    {w:"بَتْوَجَّه",sentT:253.8,t:283.43,he:"פונה",en:"I turn to",pos:"verb",root:"وجه"},
    {w:"لَكُلّ",t:284.25,he:"לכל",en:"to all",pos:null,root:null},
    {w:"الأُمَّهات",t:284.91,he:"האמהות",en:"the mothers",pos:null,root:null},
    {w:"والأَخَوات",punct:":",t:285.21,he:"והאחיות",en:"and the sisters",pos:null,root:null},
    {w:"بِدّنا",t:285.51,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"نِعْطيهُن",t:285.95,he:"ניתן להן",en:"we give them",pos:"verb",root:"عطي"},
    {w:"الميكْروفونات",t:286.35,he:"המיקרופונים",en:"the microphones",pos:null,root:null},
    {w:"والمِنَصّة",punct:"،",t:298.05,he:"והבמה",en:"and the platform",pos:null,root:null},
    {w:"وبِدّنا",t:298.61,he:"ואנחנו רוצים",en:"and we want",pos:null,root:null},
    {w:"يْجيبوا",t:298.87,he:"יביאו",en:"bring",pos:"verb",root:"جيب"},
    {w:"صُوَر",t:299.01,he:"תמונות",en:"pictures of",pos:null,root:null},
    {w:"وْلادْهُن",t:299.29,he:"הילדים שלהן",en:"their children",pos:null,root:null},
    {w:"ويْحُطّوها",punct:"،",t:299.55,he:"ויניחו אותן",en:"and place them",pos:"verb",root:"حط"},
    {w:"عَشان",t:299.67,he:"כדי ש",en:"so that",pos:null,root:null},
    {w:"يِجي",t:299.81,he:"שיבוא",en:"come",pos:"verb",root:"جي"},
    {w:"كُلّ",t:300.13,he:"כל",en:"all",pos:null,root:null},
    {w:"الشَّباب",t:302.07,he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"ويْشوفوا",t:302.63,he:"ויראו",en:"and see",pos:"verb",root:"شوف"},
    {w:"وِجوهْهُم",punct:".",t:302.91,he:"הפנים שלהם",en:"their faces",pos:null,root:null},
    {w:"مِن",sentT:264.9,t:303.05,he:"מ-",en:"from",pos:null,root:null},
    {w:"يَوم",t:303.85,he:"יום",en:"day",pos:null,root:null},
    {w:"الخَميس",he:"חמישי",en:"Thursday",pos:null,root:null},
    {w:"راح",he:"הולכים",en:"going to",pos:"verb",root:"روح"},
    {w:"نْكون",he:"נהיה",en:"we will be",pos:"verb",root:"كان"},
    {w:"هْناك",he:"שם",en:"there",pos:null,root:null},
    {sep:"—"},
    {w:"بَعِد",he:"אחרי",en:"after",pos:null,root:null},
    {w:"بْيوت",he:"בתי",en:"the houses of",pos:null,root:null},
    {w:"العَزا",he:"האבל",en:"the mourning",pos:null,root:null},
    {sep:"—"},
    {w:"بِحَديقِة",he:"בגן",en:"in the garden of",pos:null,root:null},
    {w:"الغَزازْوة",punct:"،",he:"אל-ע׳זאזווה",en:"al-Ghazazwe",pos:null,root:null},
    {w:"بْخِيمِة",he:"באוהל",en:"in the tent of",pos:null,root:null},
    {w:"الاعْتِصام",punct:".",he:"המחאה",en:"the sit-in",pos:null,root:null},
    {w:"ورَجاءً",sentT:276.2,he:"ובבקשה",en:"and please",pos:null,root:null},
    {w:"كَمان",he:"גם",en:"also",pos:null,root:null},
    {w:"مَرّة",he:"פעם",en:"once",pos:null,root:null},
    {w:"لَكُلّ",he:"לכל",en:"to all",pos:null,root:null},
    {w:"الأَخَوات",he:"האחיות",en:"the sisters",pos:null,root:null},
    {w:"والأُمَّهات",punct:":",he:"והאמהות",en:"and the mothers",pos:null,root:null},
    {w:"ساعْدونا",punct:".",he:"עזרו לנו!",en:"help us!",pos:"verb",root:"ساعد"},
    {w:"بِدّنا",sentT:281.6,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"صُوَر",he:"תמונות",en:"pictures of",pos:null,root:null},
    {w:"كُلّ",he:"כל",en:"all",pos:null,root:null},
    {w:"الشَّباب",punct:"،",he:"הצעירים",en:"the youth",pos:null,root:null},
    {w:"كُلّ",he:"כל",en:"all",pos:null,root:null},
    {w:"شَباب",he:"צעירי",en:"youth of",pos:null,root:null},
    {w:"يافا",he:"יפו",en:"Jaffa",pos:null,root:null},
    {w:"اللّي",he:"ש-",en:"who",pos:null,root:null},
    {w:"راحوا",he:"הלכו",en:"passed away",pos:"verb",root:"روح"},
    {w:"وهُمّ",he:"כשהם",en:"while they",pos:null,root:null},
    {w:"بِالتّْلاتينات",he:"בשנות השלושים לחייהם",en:"in their thirties",pos:null,root:null},
    {w:"والأَرْبَعينات",he:"והארבעים",en:"and forties",pos:null,root:null},
    {w:"مِن",he:"מ-",en:"of",pos:null,root:null},
    {w:"عُمْرهُن",punct:"؛",he:"מגילם",en:"their age",pos:null,root:null},
    {w:"بِدّنا",he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"ياها",he:"אותה",en:"it (f.)",pos:null,root:null},
    {w:"تْكون",he:"שתהיה",en:"be",pos:"verb",root:"كان"},
    {w:"بِهالخِيمة",punct:".",he:"באוהל הזה",en:"in this tent",pos:null,root:null},
    {w:"والأَهَمّ",sentT:289.2,he:"והכי חשוב",en:"and most important",pos:null,root:null},
    {w:"مِن",he:"מ-",en:"than",pos:null,root:null},
    {w:"هيك",punct:":",he:"מזה",en:"this",pos:null,root:null},
    {w:"بِدّنا",he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"قِصَصْكُن",he:"הסיפורים שלכן",en:"your (f.pl) stories",pos:null,root:null},
    {w:"تِنْحِكي",he:"יסופרו",en:"be told",pos:"verb",root:"حكي"},
    {sep:"—"},
    {w:"إيش",he:"מה",en:"what",pos:null,root:null},
    {w:"بِمْرُق",he:"עובר",en:"happens",pos:"verb",root:"مرق"},
    {w:"عَ",he:"על",en:"to",pos:null,root:null},
    {w:"الأُمّ",he:"האמא",en:"the mother",pos:null,root:null},
    {w:"لَمّا",he:"כש-",en:"when",pos:null,root:null},
    {w:"ابْنْها",he:"הבן שלה",en:"her son",pos:null,root:null},
    {w:"بِيموت",punct:".",he:"מת",en:"dies",pos:"verb",root:"موت"},
  ]},
  { start:300.4, end:326.2, label:'5:00 – 5:26', text:[
    {w:"والأَهَمّ",sentT:294.7,t:312.51,he:"והכי חשוב",en:"and most important",pos:null,root:null},
    {w:"مِن",t:313.07,he:"מ-",en:"than",pos:null,root:null},
    {w:"هادا",t:313.21,he:"זה",en:"this",pos:null,root:null},
    {w:"كُلّه",t:313.63,he:"כל זה",en:"all of this",pos:null,root:null},
    {sep:"—"},
    {w:"وين",t:314.11,he:"לאן",en:"where",pos:null,root:null},
    {w:"أَنا",t:314.63,he:"אני",en:"I",pos:null,root:null},
    {w:"رايِح",t:314.89,he:"הולך",en:"going",pos:"verb",root:"روح"},
    {w:"بِهالحَكي",t:315.31,he:"בדיבור הזה",en:"with this talk",pos:null,root:"حكي"},
    {w:"يا",t:315.39,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",punct:"؟",t:315.79,he:"חברים",en:"folks",pos:null,root:null},
    {w:"هَلَّق",t:315.95,he:"עכשיו",en:"now",pos:null,root:null},
    {w:"بَحْكي",t:316.01,he:"מדבר",en:"I speak",pos:"verb",root:"حكي"},
    {w:"لِلشَّباب",punct:".",t:316.37,he:"לצעירים",en:"to the youth",pos:null,root:null},
    {w:"صِرْتوا",sentT:315.5,t:316.95,he:"הפכתם",en:"you started",pos:"verb",root:"صار"},
    {w:"تِطْلَعوا",t:317.11,he:"יוצאים",en:"go out",pos:"verb",root:"طلع"},
    {w:"يَمين",t:317.41,he:"ימין",en:"right",pos:null,root:null},
    {w:"وتِطْلَعوا",t:317.61,he:"ויוצאים",en:"and go out",pos:"verb",root:"طلع"},
    {w:"يَسار",punct:"،",t:317.85,he:"שמאל",en:"left",pos:null,root:null},
    {w:"ولازِم",t:318.01,he:"וצריך",en:"and must",pos:null,root:null},
    {w:"تَعْرْفوا",t:320.19,he:"שתדעו",en:"that you know",pos:"verb",root:"عرف"},
    {w:"إِنّه",t:321.13,he:"ש-",en:"that",pos:null,root:null},
    {w:"ما",t:321.43,he:"לא",en:"not",pos:null,root:null},
    {w:"إِلْكُم",t:321.51,he:"יש לכם",en:"you have",pos:null,root:null},
    {w:"غير",t:322.95,he:"חוץ מ",en:"other than",pos:null,root:null},
    {w:"بَعِض",punct:".",t:323.55,he:"אחד את השני",en:"each other",pos:null,root:null},
    {w:"لِيش",t:325.65,he:"למה",en:"why",pos:null,root:null},
    {w:"نْلِفّ",t:326.25,he:"נסתובב",en:"we circle",pos:"verb",root:"لف"},
    {w:"ونْدور",punct:"؟",he:"ונסתובב",en:"and turn",pos:"verb",root:"دور"},
    {w:"ما",sentT:315.5,he:"לא",en:"not",pos:null,root:null},
    {w:"إِلْنا",he:"יש לנו",en:"we have",pos:null,root:null},
    {w:"غير",he:"חוץ מ",en:"other than",pos:null,root:null},
    {w:"بَعِض",punct:".",he:"אחד את השני",en:"each other",pos:null,root:null},
    {w:"اللّي",sentT:315.5,he:"מי ש",en:"whoever",pos:null,root:null},
    {w:"بِدّه",he:"הוא רוצה",en:"he wants",pos:null,root:null},
    {w:"يْسوقِ",he:"להוביל",en:"to lead",pos:"verb",root:"سوق"},
    {w:"الشَّباب",he:"הצעירים",en:"the youth",pos:null,root:null},
    {sep:"—"},
    {w:"هادا",he:"זה",en:"this one",pos:null,root:null},
    {w:"بِجُرّهُم",he:"מושך אותם",en:"pulls them",pos:"verb",root:"جر"},
    {w:"يَمين",he:"ימין",en:"right",pos:null,root:null},
    {w:"وهاداك",he:"וההוא",en:"and that one",pos:null,root:null},
    {w:"بِجُرّهُم",he:"מושך אותם",en:"pulls them",pos:"verb",root:"جر"},
    {w:"يَسار",he:"שמאל",en:"left",pos:null,root:null},
    {sep:"—"},
    {w:"لازِم",he:"צריך",en:"must",pos:null,root:null},
    {w:"يَعْرِف",he:"שידע",en:"know",pos:"verb",root:"عرف"},
    {w:"إِنّه",he:"ש-",en:"that",pos:null,root:null},
    {w:"ما",he:"לא",en:"not",pos:null,root:null},
    {w:"إِلْنا",he:"יש לנו",en:"we have",pos:null,root:null},
    {w:"غيرُه",punct:"،",he:"חוץ ממנו",en:"other than him",pos:null,root:null},
    {w:"وما",he:"ולא",en:"and not",pos:null,root:null},
    {w:"إِلُه",he:"יש לו",en:"he has",pos:null,root:null},
    {w:"غيرْنا",punct:".",he:"חוץ מאיתנו",en:"other than us",pos:null,root:null},
    {w:"قُلْت",punct:":",sentT:319.2,he:"אמרתי",en:"I said",pos:"verb",root:"قال"},
    {w:"يا",he:"יא",en:"O",pos:null,root:null},
    {w:"إِخْوان",punct:"،",he:"אחים",en:"brothers",pos:null,root:null},
    {w:"شو",he:"מה",en:"what",pos:null,root:null},
    {w:"هالجُنون",punct:"؟",he:"השיגעון הזה",en:"this madness",pos:null,root:"جنن"},
    {w:"شو",sentT:319.2,he:"מה",en:"what",pos:null,root:null},
    {w:"هالجُنون",punct:"؟",he:"השיגעון הזה",en:"this madness",pos:null,root:"جنن"},
  ]},
  { start:326.2, end:364.6, label:'5:26 – 6:04', text:[
    {w:"وهاي",sentT:333.7,t:341.62,he:"וזאת",en:"and this is",pos:null,root:null},
    {w:"كَمان",t:341.92,he:"גם",en:"also",pos:null,root:null},
    {w:"رِسالة",t:342.2,he:"מסר",en:"a message",pos:null,root:null},
    {w:"لِلشَّباب",punct:":",t:342.48,he:"לצעירים",en:"to the youth",pos:null,root:null},
    {w:"قَدّ",t:342.78,he:"כמה ש",en:"as much as",pos:null,root:null},
    {w:"ما",t:342.86,he:"-",en:"",pos:null,root:null},
    {w:"اخْتَلَفْنا",punct:"،",t:343.12,he:"התווכחנו",en:"we disagreed",pos:"verb",root:"اختلف"},
    {w:"وقَدّ",t:343.48,he:"וכמה ש",en:"and as much as",pos:null,root:null},
    {w:"ما",t:343.8,he:"-",en:"",pos:null,root:null},
    {w:"بْنِحِبّكُم",t:344.18,he:"אנחנו אוהבים אתכם",en:"we love you",pos:"verb",root:"حب"},
    {sep:"—"},
    {w:"وواللَّه",t:344.32,he:"ובאלוהים אני נשבע",en:"and I swear",pos:null,root:null},
    {w:"إِنّنا",t:344.5,he:"ש-אנחנו",en:"that we",pos:null,root:null},
    {w:"بْنِحِبّكُم",t:347.92,he:"אנחנו אוהבים אתכם",en:"we love you",pos:"verb",root:"حب"},
    {sep:"—"},
    {w:"لا",t:348.52,he:"אל",en:"don't",pos:null,root:null},
    {w:"تِتْصَرَّفوا",t:348.92,he:"תתנהגו",en:"behave",pos:"verb",root:"تصرف"},
    {w:"كَأَنّه",t:349.38,he:"כאילו",en:"as if",pos:null,root:null},
    {w:"كُلّ",t:349.66,he:"כל",en:"every",pos:null,root:null},
    {w:"واحَد",t:350.3,he:"אחד",en:"one",pos:null,root:null},
    {w:"مِنكُم",t:351.26,he:"מכם",en:"of you",pos:null,root:null},
    {w:"لَحالُه",t:351.56,he:"לבד",en:"alone",pos:null,root:null},
    {w:"بِهالبَلَد",punct:".",t:352.06,he:"בארץ הזאת",en:"in this land",pos:null,root:null},
    {w:"بِدّنا",sentT:338.5,t:352.5,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"اِيّاكُم",t:361.54,he:"אתכם",en:"you",pos:null,root:null},
    {w:"تِمْشوا",t:362.22,he:"תלכו",en:"to walk",pos:"verb",root:"مشي"},
    {w:"عَ",t:362.46,he:"לפי",en:"along",pos:null,root:null},
    {w:"اللّي",t:362.82,he:"מה ש",en:"what",pos:null,root:null},
    {w:"رَسَمْناه",punct:".",t:362.92,he:"תכננו",en:"we planned",pos:"verb",root:"رسم"},
    {w:"بِدّنا",sentT:341.4,t:363.16,he:"אנחנו רוצים",en:"we want",pos:null,root:null},
    {w:"اِيّاكُم",t:363.48,he:"אתכם",en:"you",pos:null,root:null},
    {w:"تيجوا",t:363.82,he:"תבואו",en:"to come",pos:"verb",root:"جي"},
    {w:"تْقولوا",t:363.96,he:"ותגידו",en:"and say",pos:"verb",root:"قال"},
    {w:"إِنّه",t:364.38,he:"ש-",en:"that",pos:null,root:null},
    {w:"مَعْكُم",t:365.26,he:"יש אתכם",en:"you have",pos:null,root:null},
    {w:"أَرْبَعة",punct:"،",t:365.94,he:"ארבעה",en:"four",pos:null,root:null},
    {w:"خَمْس",t:366.14,he:"חמישה",en:"five",pos:null,root:null},
    {w:"أَصْحاب",t:366.7,he:"חברים",en:"friends",pos:null,root:null},
    {w:"اضْطَرَّيْتوا",t:367.28,he:"נאלצתם",en:"you were forced",pos:"verb",root:"اضطر"},
    {w:"تِدْفْنوهُم",punct:".",t:367.8,he:"לקבור אותם",en:"to bury them",pos:"verb",root:"دفن"},
    {w:"هاي",sentT:344.4,t:368.02,he:"זאת",en:"this is",pos:null,root:null},
    {w:"مِش",t:368.44,he:"לא",en:"not",pos:null,root:null},
    {w:"حَياة",punct:".",he:"חיים",en:"life",pos:null,root:null},
    {w:"بِتَعْرْفوا",sentT:349.7,he:"אתם יודעים",en:"you know",pos:"verb",root:"عرف"},
    {w:"الموقِفِ",he:"המצב",en:"the situation",pos:null,root:"وقف"},
    {w:"المُحْرِج",he:"המביך",en:"embarrassing",pos:null,root:null},
    {w:"لَمّا",he:"כש-",en:"when",pos:null,root:null},
    {w:"صاحِبْكُم",he:"החבר שלכם",en:"your friend",pos:null,root:null},
    {w:"بِنْقِتِل",punct:"،",he:"נהרג",en:"is killed",pos:"verb",root:"قتل"},
    {w:"وبَعِد",he:"ואחרי",en:"and after",pos:null,root:null},
    {w:"سِنين",he:"שנים",en:"years",pos:null,root:null},
    {w:"بِتْشوفوا",he:"אתם רואים",en:"you see",pos:"verb",root:"شوف"},
    {w:"أُمّه",he:"אמא שלו",en:"his mother",pos:null,root:null},
    {sep:"—"},
    {w:"إيش",he:"מה",en:"what",pos:null,root:null},
    {w:"بِدّكُم",he:"אתם רוצים",en:"you want",pos:null,root:null},
    {w:"تْقولولْها",punct:"؟",he:"תגידו לה",en:"tell her",pos:"verb",root:"قال"},
    {w:"فَإِنْتو",sentT:355,he:"אז אתם",en:"so you",pos:null,root:null},
    {w:"كَمان",he:"גם",en:"also",pos:null,root:null},
    {w:"عَلَيْكُم",he:"עליכם",en:"you have",pos:null,root:null},
    {w:"مَسْؤولِيِّة",he:"אחריות",en:"responsibility",pos:null,root:null},
    {w:"إِنّكُم",he:"ש-אתם",en:"that you",pos:null,root:null},
    {w:"تِحْكوا",he:"תדברו",en:"speak",pos:"verb",root:"حكي"},
    {w:"لِأَصْحابْكُم",punct:":",he:"לחברים שלכם",en:"to your friends",pos:null,root:null},
    {w:"لَوين",he:"לאן",en:"where",pos:null,root:null},
    {w:"رايْحين",punct:"؟",he:"הולכים",en:"going",pos:"verb",root:"روح"},
  ]},
  { start:364.6, end:385.8, label:'6:04 – 6:25', text:[
    {w:"وعِنّي",sentT:359.9,t:361.54,he:"ויש לי",en:"and I have",pos:null,root:null},
    {w:"إِلْكُم",t:362.22,he:"לכם",en:"for you",pos:null,root:null},
    {w:"مُعْطى",t:362.46,he:"נתון",en:"a piece of information",pos:null,root:null},
    {sep:"—"},
    {w:"مُعْطى",t:362.82,he:"נתון",en:"information",pos:null,root:null},
    {w:"جْديد",t:362.92,he:"חדש",en:"new",pos:null,root:null},
    {w:"وِصِلْنا",t:363.16,he:"הגיע אלינו",en:"reached us",pos:"verb",root:"وصل"},
    {w:"مِن",t:363.48,he:"מ-",en:"from",pos:null,root:null},
    {w:"البَلَدِيِّة",punct:"،",t:363.82,he:"העירייה",en:"the municipality",pos:null,root:null},
    {w:"مِن",t:363.96,he:"מ-",en:"from",pos:null,root:null},
    {w:"الإدارة",t:364.38,he:"ההנהלה",en:"the administration",pos:null,root:null},
    {w:"العُلْيا",punct:":",t:367.28,he:"העליונה",en:"the senior",pos:null,root:null},
    {w:"تَعْرْفوا",t:367.8,he:"אתם יודעים",en:"do you know",pos:"verb",root:"عرف"},
    {w:"قَدّيش",t:368.02,he:"כמה",en:"how much",pos:null,root:null},
    {w:"عُمِر",t:368.44,he:"גיל",en:"the age of",pos:null,root:null},
    {w:"اللّي",t:368.62,he:"מי ש",en:"whoever",pos:null,root:null},
    {w:"عَمبِيخَطّْطوا",t:368.98,he:"מתכננים",en:"planning",pos:"verb",root:"خطط"},
    {w:"لَهالإِشْيا",punct:"؟",t:369.6,he:"לדברים האלה",en:"these things",pos:null,root:null},
    {w:"تِسْعَطاشَر",t:370.02,he:"תשע עשרה",en:"nineteen",pos:null,root:null},
    {w:"سَنة",punct:".",t:370.22,he:"שנה",en:"years old",pos:null,root:null},
    {w:"تِسْعَطاشَر",t:370.48,he:"תשע עשרה",en:"nineteen",pos:null,root:null},
    {w:"سَنة",punct:".",t:376.1,he:"שנה",en:"years old",pos:null,root:null},
    {w:"وبَعِض",sentT:375.1,t:376.78,he:"וכמה מ",en:"and some of",pos:null,root:null},
    {w:"المُجْرِمين",t:377.32,he:"הפושעים",en:"the criminals",pos:null,root:"جرم"},
    {w:"عَمبِيسْتَغِلّوا",t:377.48,he:"מנצלים",en:"exploiting",pos:"verb",root:"استغل"},
    {w:"هالوْلاد",punct:".",t:377.96,he:"הילדים האלה",en:"these children",pos:null,root:null},
    {w:"خافوا",sentT:379.2,t:378.48,he:"פחדו!",en:"fear!",pos:"verb",root:"خاف"},
    {w:"اللَّه",punct:"،",t:378.82,he:"אלוהים",en:"God",pos:null,root:null},
    {w:"خافوا",t:379.2,he:"פחדו!",en:"fear!",pos:"verb",root:"خاف"},
    {w:"اللَّه",punct:".",t:382.5,he:"אלוהים",en:"God",pos:null,root:null},
    {w:"لَوين",sentT:379.2,t:384.67,he:"לאן",en:"where",pos:null,root:null},
    {w:"رايْحين",punct:"؟",t:384.97,he:"הולכים",en:"going",pos:"verb",root:"روح"},
  ]},
  { start:385.8, end:410, label:'6:25 – 6:50', text:[
    {w:"يا",sentT:385.8,t:396.59,he:"יא",en:"O",pos:null,root:null},
    {w:"جَماعة",punct:"،",t:397.31,he:"חברים",en:"folks",pos:null,root:null},
    {w:"فيكُم",t:397.55,he:"בכם",en:"in you",pos:null,root:null},
    {w:"العافْية",punct:"،",t:398.15,he:"הבריאות",en:"health",pos:null,root:null},
    {w:"وشُكْراً",t:398.71,he:"ותודה",en:"and thanks",pos:null,root:null},
    {w:"إِلْكُم",punct:".",t:399.15,he:"לכם",en:"to you",pos:null,root:null},
    {w:"رَجاءً",sentT:390.4,t:399.73,he:"בבקשה",en:"please",pos:null,root:null},
    {w:"رَجاءً",t:400.09,he:"בבקשה",en:"please",pos:null,root:null},
    {w:"رَجاءً",t:400.35,he:"בבקשה",en:"please",pos:null,root:null},
    {sep:"—"},
    {w:"لا",t:400.77,he:"אל",en:"don't",pos:null,root:null},
    {w:"تِيْأَسوا",punct:".",t:401.17,he:"תתייאשו",en:"despair!",pos:"verb",root:"يأس",sharedRoot:true},
    {w:"لا",t:401.35,he:"אל",en:"don't",pos:null,root:null},
    {w:"تِيْأَسوا",punct:".",t:401.79,he:"תתייאשו",en:"despair!",pos:"verb",root:"يأس",sharedRoot:true},
    {w:"احْنا",sentT:397.6,t:402.15,he:"אנחנו",en:"we",pos:null,root:null},
    {w:"هون",punct:"،",t:403.51,he:"כאן",en:"here",pos:null,root:null},
    {w:"واحْنا",t:404.23,he:"ואנחנו",en:"and we",pos:null,root:null},
    {w:"باقْيين",punct:"،",t:404.59,he:"נשארים",en:"remaining",pos:"verb",root:"بقي"},
    {w:"واحْنا",t:404.93,he:"ואנחנו",en:"and we",pos:null,root:null},
    {w:"اتْحَدَّيْنا",t:405.19,he:"התמודדנו",en:"we've challenged",pos:"verb",root:"تحدى"},
    {w:"قَبِل",punct:"،",t:405.53,he:"לפני",en:"before",pos:null,root:null},
    {w:"وراح",t:405.69,he:"ונלך ל-",en:"and will",pos:"verb",root:"روح"},
    {w:"نِتْحَدّى",t:405.99,he:"נתמודד",en:"we'll challenge",pos:"verb",root:"تحدى"},
    {w:"اليَوم",punct:"،",t:406.27,he:"היום",en:"today",pos:null,root:null},
    {w:"وراح",t:410.23,he:"ונלך ל-",en:"and will",pos:"verb",root:"روح"},
    {w:"نِتْحَدّى",t:410.95,he:"נתמודד",en:"we'll challenge",pos:"verb",root:"تحدى"},
    {w:"بُكْرا",punct:"،",t:411.23,he:"מחר",en:"tomorrow",pos:null,root:null},
    {w:"واحْنا",t:412.33,he:"ואנחנו",en:"and we",pos:null,root:null},
    {w:"قَدّها",punct:".",t:413.21,he:"עומדים בזה",en:"up to it",pos:null,root:null},
    {w:"واللّي",sentT:401.9,he:"ומי ש",en:"and whoever",pos:null,root:null},
    {w:"عَجَبُه",he:"מוצא חן בעיניו",en:"is pleased by it",pos:"verb",root:"عجب"},
    {w:"عَجَبُه",punct:"،",he:"מוצא חן בעיניו",en:"is pleased",pos:"verb",root:"عجب"},
    {w:"واللّي",he:"ומי ש",en:"and whoever",pos:null,root:null},
    {w:"مِش",he:"לא",en:"not",pos:null,root:null},
    {w:"عاجْبُه",he:"לא מוצא חן בעיניו",en:"isn't pleased",pos:"verb",root:"عجب"},
    {w:"هاي",he:"זה",en:"this is",pos:null,root:null},
    {w:"بَحِر",he:"ים",en:"sea",pos:null,root:"بحر",sharedRoot:true},
    {w:"يافا",he:"יפו",en:"Jaffa",pos:null,root:null},
    {w:"يِشْرَب",he:"ישתה",en:"let him drink",pos:"verb",root:"شرب"},
    {w:"مِنّه",punct:".",he:"ממנו",en:"from it",pos:null,root:null},
    {w:"واحْنا",sentT:401.9,he:"ואנחנו",en:"and we",pos:null,root:null},
    {w:"مَوْجودين",punct:".",he:"נמצאים",en:"present",pos:"verb",root:"وجد"},
    {w:"وبارَك",sentT:406.4,he:"ובירך",en:"and blessed",pos:"verb",root:"برك"},
    {w:"اللَّه",he:"אלוהים",en:"God",pos:null,root:null},
    {w:"فيكُم",punct:".",he:"אתכם",en:"you",pos:null,root:null},
  ]},
];

const PHRASE_GLOSSES = [
  {
    keys: [
      "مِش",
      "طَبيعي"
    ],
    he: "לא נורמלי",
    en: "not normal",
    type: "idiom"
  },
  {
    keys: [
      "يا",
      "جَماعة"
    ],
    he: "יא ג׳מאעה — פנייה לקהל",
    en: "hey everyone",
    type: null
  },
  {
    keys: [
      "فيكُم",
      "العافْية"
    ],
    he: "תודה רבה, בריאות לכם — ברכה נפוצה",
    en: "thank you / bless you",
    type: "idiom"
  },
  {
    keys: [
      "خافوا",
      "اللَّه"
    ],
    he: "יראו שמיים, תיזהרו — ביטוי נפוץ",
    en: "fear God",
    type: "idiom"
  },
  {
    keys: [
      "وين",
      "رايحين"
    ],
    he: "לאן הולכים?",
    en: "where are you going?",
    type: "idiom"
  },
  {
    keys: [
      "لَوين",
      "رايْحين"
    ],
    he: "לאן הולכים?",
    en: "where are you going?",
    type: "idiom"
  },
  {
    keys: [
      "لا",
      "تِيْأَسوا"
    ],
    he: "אל תתייאשו",
    en: "don't despair",
    type: "idiom"
  },
  {
    keys: [
      "بَحِر",
      "يافا"
    ],
    he: "ים יפו — כינוי לדבר נצחי",
    en: "the sea of Jaffa",
    type: "proverb"
  },
  {
    keys: [
      "شو",
      "هالجُنون"
    ],
    he: "מה השיגעון הזה",
    en: "what is this madness",
    type: "idiom"
  }
];
