/* ─────────────── VOICEOVER DATA ───────────────
   Generated by scripts/generate-voiceover.js — do not hand-edit.
   Re-run that script after any change to CHUNKS in lesson-data.js to regenerate
   both the audio file and this file together, so text and audio stay in sync.

   VOICEOVER_SRC   — path to the generated lesson-length MP3, or null if not yet generated.
   VOICEOVER_CHUNKS — same shape as CHUNKS' {start,end} pairs, but timed to the voiceover
                      audio instead of the original recording (the two have different pacing).
*/
const VOICEOVER_SRC = null;
const VOICEOVER_CHUNKS = null;
